from django.db import models


class Product(models.Model):
    business = models.ForeignKey('businesses.Business', on_delete=models.CASCADE, related_name='products')
    vendor = models.ForeignKey('marketplace.Vendor', on_delete=models.SET_NULL, null=True, blank=True, related_name='products')
    marketplace_category = models.ForeignKey('marketplace.MarketplaceCategory', on_delete=models.SET_NULL, null=True, blank=True, related_name='products')
    name = models.CharField(max_length=255)
    slug = models.SlugField(blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    sale_price = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    currency = models.CharField(max_length=10, default='BDT')
    stock_quantity = models.IntegerField(default=0)
    stock_status = models.CharField(max_length=40, default='in_stock')
    sku = models.CharField(max_length=120, blank=True)
    category = models.CharField(max_length=120, blank=True)
    delivery_info = models.TextField(blank=True)
    return_policy = models.TextField(blank=True)
    warranty_info = models.TextField(blank=True)
    image_url = models.URLField(blank=True)
    gallery = models.JSONField(default=list, blank=True)
    approval_status = models.CharField(max_length=20, default='draft')
    is_active = models.BooleanField(default=True)
    embedding_status = models.CharField(max_length=20, default='pending')
    metadata = models.JSONField(default=dict, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
