from django.urls import path

from . import views

urlpatterns = [
    path("vendors/", views.vendors),
    path("vendors/<int:vendor_id>/", views.vendor_detail),
    path("vendors/<int:vendor_id>/approve/", views.vendor_approve),
    path("vendors/<int:vendor_id>/reject/", views.vendor_reject),
    path("vendors/<int:vendor_id>/suspend/", views.vendor_suspend),
    path("vendors/<int:vendor_id>/activate/", views.vendor_activate),
    path("vendors/<int:vendor_id>/commission/", views.vendor_commission),
    path("marketplace/categories/", views.marketplace_categories),
    path("marketplace/categories/<int:category_id>/", views.marketplace_category_detail),
    path("marketplace/products/", views.marketplace_products),
    path("marketplace/products/<int:product_id>/approve/", views.marketplace_product_approve),
    path("marketplace/products/<int:product_id>/reject/", views.marketplace_product_reject),
    path("marketplace/orders/", views.marketplace_orders),
    path("marketplace/orders/<int:order_id>/", views.marketplace_order_detail),
    path("marketplace/orders/<int:order_id>/status/", views.marketplace_order_status),
    path("marketplace/orders/export/", views.marketplace_orders_export),
    path("marketplace/orders/demo-create/", views.marketplace_orders_demo_create),
    path("marketplace/commissions/", views.marketplace_commissions),
    path("marketplace/payouts/", views.marketplace_payouts),
    path("marketplace/payouts/<int:payout_id>/mark-paid/", views.marketplace_payout_mark_paid),
    path("marketplace/payouts/export/", views.marketplace_payouts_export),
    path("marketplace/analytics/overview/", views.marketplace_analytics_overview),
    path("marketplace/analytics/export/", views.marketplace_analytics_export),
    path("marketplace/settings/", views.marketplace_settings),
    path("vendor/dashboard/", views.vendor_dashboard),
    path("vendor/products/", views.vendor_products),
    path("vendor/products/<int:product_id>/", views.vendor_product_detail),
    path("vendor/products/<int:product_id>/submit-approval/", views.vendor_product_submit_approval),
    path("vendor/products/reindex/", views.vendor_products_reindex),
    path("vendor/orders/", views.vendor_orders),
    path("vendor/orders/<int:order_id>/", views.vendor_order_detail),
    path("vendor/orders/<int:order_id>/status/", views.vendor_order_status),
    path("vendor/tickets/", views.vendor_tickets),
    path("vendor/tickets/<int:ticket_id>/", views.vendor_ticket_detail),
    path("vendor/tickets/<int:ticket_id>/comments/", views.vendor_ticket_comment),
    path("vendor/tickets/<int:ticket_id>/status/", views.vendor_ticket_status),
    path("vendor/faqs/", views.vendor_faqs),
    path("vendor/faqs/<int:faq_id>/", views.vendor_faq_detail),
    path("vendor/faqs/reindex/", views.vendor_faqs_reindex),
    path("vendor/payouts/", views.vendor_payouts),
    path("vendor/payouts/request/", views.vendor_payout_request),
    path("vendor/settings/", views.vendor_settings),
    path("storefront/orders/", views.storefront_create_order),
    path("storefront/orders/<str:order_number>/", views.storefront_order_detail),
]
