# Generated by Django 5.2.14 on 2026-05-06 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIInteractionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_message', models.TextField()),
                ('ai_reply', models.TextField(blank=True)),
                ('confidence', models.FloatField(default=0.0)),
                ('intent', models.CharField(default='general', max_length=80)),
                ('sentiment', models.CharField(default='neutral', max_length=40)),
                ('escalated', models.BooleanField(default=False)),
                ('escalation_reason', models.CharField(default='none', max_length=120)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_logs', to='businesses.business')),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='conversations.conversation')),
            ],
        ),
    ]
