# Generated by Django 5.2.14 on 2026-05-06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_gateway', '0001_initial'),
        ('businesses', '0001_initial'),
        ('conversations', '0002_agent_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_text', models.TextField()),
                ('output_text', models.TextField(blank=True)),
                ('intent', models.CharField(default='general', max_length=80)),
                ('sentiment', models.CharField(default='neutral', max_length=40)),
                ('confidence', models.FloatField(default=0.0)),
                ('sources', models.JSONField(blank=True, default=list)),
                ('model_name', models.CharField(default='mock', max_length=120)),
                ('latency_ms', models.IntegerField(default=0)),
                ('status', models.CharField(default='ok', max_length=20)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_request_logs', to='businesses.business')),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='conversations.conversation')),
            ],
        ),
    ]
