# Generated by Django 5.2.14 on 2026-05-06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_gateway', '0002_ai_request_log'),
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAssistantSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_reply_enabled', models.BooleanField(default=True)),
                ('confidence_threshold', models.FloatField(default=0.75)),
                ('business_tone', models.CharField(default='professional', max_length=40)),
                ('language', models.CharField(default='mixed', max_length=20)),
                ('rule_refund', models.BooleanField(default=True)),
                ('rule_negative_sentiment', models.BooleanField(default=True)),
                ('rule_below_confidence', models.BooleanField(default=True)),
                ('rule_customer_requests_human', models.BooleanField(default=True)),
                ('system_prompt', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_settings', to='businesses.business')),
            ],
        ),
    ]
