# Generated by Django 5.2.12 on 2026-05-06 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingplan',
            name='agent_limit',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='ai_reply_limit',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='channels_allowed',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='order_limit',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='product_limit_per_vendor',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='vendor_limit',
            field=models.IntegerField(default=3),
        ),
    ]
