# Generated by Django 5.2.14 on 2026-05-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_agent_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('waiting_human', 'Waiting Human'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='active', max_length=20),
        ),
        migrations.AddField(model_name='message', name='confidence', field=models.FloatField(default=0.0)),
        migrations.AddField(model_name='message', name='intent', field=models.CharField(blank=True, max_length=80)),
        migrations.AddField(model_name='message', name='metadata', field=models.JSONField(blank=True, default=dict)),
        migrations.AddField(model_name='message', name='sentiment', field=models.CharField(blank=True, max_length=40)),
        migrations.AlterField(
            model_name='message',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('ai', 'AI'), ('agent', 'Agent'), ('system', 'System'), ('user', 'User'), ('assistant', 'Assistant')], max_length=20),
        ),
    ]
