# Generated by Django 5.2.14 on 2026-05-06 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='embedding_vector',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
