# Generated by Django 5.2.14 on 2026-05-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0002_faq_embedding_vector'),
    ]

    operations = [
        migrations.AddField(model_name='faq', name='category', field=models.CharField(blank=True, max_length=120)),
        migrations.AddField(model_name='faq', name='embedding_status', field=models.CharField(default='pending', max_length=20)),
        migrations.AddField(model_name='faq', name='language', field=models.CharField(default='bn', max_length=10)),
        migrations.AddField(model_name='faq', name='tags', field=models.JSONField(blank=True, default=list)),
    ]
