# Generated by Django 5.2.14 on 2026-05-06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessengerIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.CharField(max_length=128, unique=True)),
                ('page_access_token', models.CharField(max_length=500)),
                ('app_id', models.CharField(blank=True, max_length=128)),
                ('app_secret', models.CharField(blank=True, max_length=255)),
                ('verify_token', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='messenger_integration', to='businesses.business')),
            ],
        ),
    ]
