# Generated by Django 5.2.12 on 2026-05-06 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('marketplace', '0001_initial'),
        ('products', '0003_product_approval_status_product_gallery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='last_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_customers', to='marketplace.order'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='last_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_customers', to='products.product'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='marketplace.vendor'),
        ),
    ]
