# Generated by Django 5.2.12 on 2026-05-06 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
        ('products', '0003_product_approval_status_product_gallery_and_more'),
        ('tickets', '0003_ticket_priority_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='assignment_type',
            field=models.CharField(default='marketplace', max_length=20),
        ),
        migrations.AddField(
            model_name='ticket',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='marketplace.order'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='products.product'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='marketplace.vendor'),
        ),
    ]
