# Generated by Django 5.2.14 on 2026-05-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(model_name='product', name='category', field=models.CharField(blank=True, max_length=120)),
        migrations.AddField(model_name='product', name='delivery_info', field=models.TextField(blank=True)),
        migrations.AddField(model_name='product', name='embedding_status', field=models.CharField(default='pending', max_length=20)),
        migrations.AddField(model_name='product', name='image_url', field=models.URLField(blank=True)),
        migrations.AddField(model_name='product', name='return_policy', field=models.TextField(blank=True)),
        migrations.AddField(model_name='product', name='stock_status', field=models.CharField(default='in_stock', max_length=40)),
        migrations.AddField(model_name='product', name='warranty_info', field=models.TextField(blank=True)),
    ]
